### ISSUE TITLE
Checkout Stagehand 1.1.0

### ISSUE THREAD

**Issue by joelschutz** [kharism/hanashi#4]
I was very happy to see that you choose to use my library to make your game. It made me feel very proud of myself and very less anxious about spending so much of my free time in it 🥲

I saw that you are managing events and using callback, but I'd suggest you check out the new "Scene director" feature, maybe it can simplify some things. Also I think it can be useful for your dialog system to define it like a statemachine, so you can have a more predictable path through the scenes.

Keep on the great job. Good luck!

**Comment by kharism** [comment]
Thank you. I'll put it on backlog.
